"""empty message

Revision ID: 16659fd892
Revises: 3c1fd9351
Create Date: 2015-06-23 16:46:12.722345

"""

# revision identifiers, used by Alembic.
revision = '16659fd892'
down_revision = '3c1fd9351'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
