"""empty message

Revision ID: 320bca1fc35
Revises: 354a51c6a9b
Create Date: 2015-05-28 12:59:19.230548

"""

# revision identifiers, used by Alembic.
revision = '320bca1fc35'
down_revision = '354a51c6a9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('instance_name', sa.String(), nullable=True))
    op.drop_column('service', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('service', 'instance_name')
    ### end Alembic commands ###
