"""empty message

Revision ID: 3ee2bf3065a
Revises: d869ae3c6
Create Date: 2015-05-20 16:05:50.841273

"""

# revision identifiers, used by Alembic.
revision = '3ee2bf3065a'
down_revision = 'd869ae3c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
