"""empty message

Revision ID: d869ae3c6
Revises: None
Create Date: 2015-05-18 21:09:38.941041

"""

# revision identifiers, used by Alembic.
revision = 'd869ae3c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota',
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_table('data',
    sa.Column('quota', sa.String(), nullable=False),
    sa.Column('date_collected', sa.Date(), nullable=False),
    sa.Column('memory_limit', sa.Integer(), nullable=True),
    sa.Column('total_routes', sa.Integer(), nullable=True),
    sa.Column('total_services', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quota'], ['quota.guid'], ),
    sa.PrimaryKeyConstraint('quota', 'date_collected', name='quota_guid_date')
    )
    op.create_table('service',
    sa.Column('quota', sa.String(), nullable=False),
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('date_collected', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quota'], ['quota.guid'], ),
    sa.PrimaryKeyConstraint('quota', 'guid', 'date_collected', name='quota_serviceguid_date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    op.drop_table('data')
    op.drop_table('quota')
    ### end Alembic commands ###
